### ISSUE TITLE
Listing package at https://gap-packages.github.io/

### ISSUE THREAD

**Issue by alex-konovalov** [danielrademacher/BruhatDecomposition2#2]
@danielrademacher we maintain a list of GAP packages with their public repositories at https://gap-packages.github.io/ - would you like this package to be listed there? It's not limited to packages redistributed with GAP - the aim is to list all packages independently of their status. This will help others to find them (I discovered this package today reading a comment at https://math.stackexchange.com/questions/4108573/bruhat-decomposition-in-gap/4113371#4113371).

**Comment by danielrademacher** [comment]
Hello Alex,
Yes, this would be great :) Thanks for asking me! If you need more information about the package, I would be happy to give them.

**Comment by alex-konovalov** [comment]
Done in https://github.com/gap-packages/gap-packages.github.io/commit/e7f68171d6670c7aaaac6dde3dd5124be1a19d84. 

That page autogenerates the part about packages from https://github.com/gap-packages organisation, picking up the `Subtitle` from their PackageInfo.g, so I just did the same, thanks!
