### ISSUE TITLE
why does BruhatDecompositionSp fail for some matrices

### ISSUE THREAD

**Issue by qodesign** [danielrademacher/BruhatDecomposition2#4]
I've been using the package for some time and works well most of the time. However for some matrices it seems to fail.
In the gap code running Tst(1) works; Tst(2) fails  : slp[1]=fail; in both cases I check that the matrix is in Sp(2n,2):

LoadPackage("BruhatDecomposition","0");
SetInfoLevel(InfoBruhat,0);

Tst:=function(mode)local mat,n,stdgens,slp;

if(mode=1)then
 n:=5;
 mat:=[
  [0,0,0,0,0,0,0,0,0,1],
  [0,0,0,0,0,0,0,0,1,0],
  [0,0,0,0,0,0,0,1,0,0],
  [0,0,0,0,0,0,1,0,0,0],
  [0,0,0,0,1,0,0,1,1,0],
  [0,0,0,0,0,1,1,1,1,1],
  [0,0,0,1,1,0,0,0,1,1],
  [0,0,1,0,1,1,1,1,1,0],
  [0,1,0,0,1,1,0,1,1,1],
  [1,0,0,0,1,0,1,1,0,0]]*Z(2);
fi;

if(mode=2)then
 n:=4;
 mat:=[
 [1,0,0,0,0,0,0,0],
 [0,1,0,0,0,0,0,0],
 [0,0,1,0,0,0,0,0],
 [1,1,1,1,0,0,0,0],
 [0,0,0,0,1,0,0,0],
 [0,0,0,0,1,1,0,0],
 [0,0,0,0,1,0,1,0],
 [0,0,0,0,1,0,0,1]]*Z(2);
fi;

Print(" mat in Sp(2n,2)? : ",mat in Sp(2*n,2),"\n");

stdgens:=LGOStandardGensSpEvenChar(2*n,2);
slp:=BruhatDecompositionSp(stdgens,mat);

return slp;
end;

**Comment by danielrademacher** [comment]
Hi @qodesign !

Thanks a lot for the issue and for using this package. You are absolutely right, there were an error in the glueing process of the different MSLP. This should be fixed now. 

If you encounter other errors or have improvement ideas, feel free to contact me.

Best wishes
Daniel Rademacher

**Comment by qodesign** [comment]
On my side the examples that failed before now work. Thanks for fixing this so quickly.
